name: TPK8S Gitops
run-name: ${{ github.actor }} building app
on:
  push:
    branches:
      - "gitops-demo"
jobs:
  gitops-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tanzu CLI
        run: |
          export TANZU_CLI_CEIP_OPT_IN_PROMPT_ANSWER=no
          wget https://github.com/vmware-tanzu/tanzu-cli/releases/download/v1.3.0/tanzu-cli-linux-amd64.tar.gz -O /tmp/tanzu.tar.gz
          tar -xvf /tmp/tanzu.tar.gz -C /tmp
          install /tmp/v1.3.0/tanzu-cli-linux_amd64 /usr/local/bin/tanzu
          tanzu config eula accept
          tanzu init
          tanzu version

      - name: Install tanzu plugins
        run: |
          tanzu plugin install --group vmware-tanzu/app-developer

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}


      - name: Checkout gitops repo
        uses: actions/checkout@v4
        with:
          repository: warroyo/tpk8s-argo-gitops-demo
          path: gitops
          token: ${{ secrets.GH_PAT }}

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
            
      - name: Build the app and promote it to the dev space
        env:
          TANZU_API_TOKEN: ${{ secrets.API_TOKEN }}
          TANZU_CLI_CLOUD_SERVICES_ORGANIZATION_ID: 77aee83b-308f-4c8e-b9c4-3f7a6f19ba75
        run: |
            tanzu login
            tanzu project use AMER-West
            tanzu space use dev-sbx
            tanzu build config --build-plan-source-type=ucp --containerapp-registry ghcr.io/{contact.team}/{name}
            tanzu build -o ./deploy 
            tree
            tanzu promote --from-build ./deploy --to ./gitops/gitops/amer-west/spaces/gitops-dev
      

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: "dev-${{github.run_attempt}}"
          commit_message: push application deployment to dev
          commit_user_name: warroyo
          create_branch: true
          repository: ./gitops
          
      - name: create pull request
        run: gh pr create --repo warroyo/tpk8s-argo-gitops-demo -B main -H dev-${{github.run_attempt}} --title 'dev deployment' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - run: echo "üçè This job's status is ${{ job.status }}."
